### PR TITLE
Store and replay the last 25 output messages on incoming log and control connections.

### PR DESCRIPTION
**Pull request by gitwart**

### CODE REVIEW

**Comment by gitwart** [comment]
Requires boost development package to build, due to the use of boost::circular_buffer

**Comment by ralphlange** [comment]
How does that affect portability (Mac, Windows)?

**Comment by gitwart** [comment]
I do not have access to a Mac, Windows dev box, so I would need someone else to test on those platforms.

**Comment by ralphlange** [comment]
I have access to a Windows box, and I know someone who knows how to spell Apple...

**Comment by ralphlange** [comment]
Generally, Boost should be available.

**Comment by ralphlange** [comment]
Hey - the Apple CI build worked out of the box!

**Comment by gitwart** [comment]
Superseded by #61

**Pull request closed without merging**
