### PR TITLE
Make signal handling safe using pselect.

### PR DESCRIPTION
**Pull request by ambrop72**
It is unsafe to use printf from signal handlers and to reopen the log file.
This should resolve the hazards by keeping SIGTERM/SIGHUP/SIGPIPE blocked, except in pselect where these are atomically unblocked.
Just after pselect returns, the signal flags are checked to see if any signal handler has been executed pselect.

### CODE REVIEW

**Comment by ralphlange** [comment]
I would assume portability issues with pselect(), at least on BSD and MacOS. Have you checked one of these platforms?

**Comment by ambrop72** [comment]
Hi Ralph,
This is standard POSIX stuff so I didn't really think about it.
Some googling suggests that:
- FreeBSD, OpenBSD and NetBSD do have pselect. FreeBSD specifically has has it since 5.0 (ancient).
- OSX also has it. But I found this issue report: http://stackoverflow.com/questions/14045801/different-pselect-behaviour-on-osx-vs-linux . Which boils down to, we may get stuck in pselect() after a signal handler was invoked without getting a chance to detect the signal from the main loop. In our case I think this is already a possibility with the current code anyway. In the worst case the processing of the signal would be delayed by 0.5s (the select timeout), so I wouldn't worry about it.

**Comment by ralphlange** [comment]
About five years ago I had to change procServ to use select() instead of poll(), because OSXs poll() implementation is broken.
My impression was that OSX split from FreeBSD at a very early point. Maybe even before "ancient"?

In this case, however, I agree that it shouldn't worsen the current behavior. Merging.

**Comment by ambrop72** [comment]
Thank you!

**Pull request merged**
